// Code generated by cmd/cgo -godefs; DO NOT EDIT.

package term

const (
	ftOK                      = 0x0
	ftInvalidHandle           = 0x1
	ftDeviceNotFound          = 0x2
	ftDeviceNotOpened         = 0x3
	ftIOError                 = 0x4
	ftInsufficientResources   = 0x5
	ftInvalidParameter        = 0x6
	ftInvalidBaudRate         = 0x7
	ftDeviceNotOpenedForErase = 0x8
	ftDeviceNotOpenedForWrite = 0x9
	ftFailedToWriteDevice     = 0xa
	ftEEPROMReadFailed        = 0xb
	ftEEPROMWriteFailed       = 0xc
	ftEEPROMEraseFailed       = 0xd
	ftEEPROMNotPresent        = 0xe
	ftEEPROMNotProgrammed     = 0xf
	ftInvalidArgs             = 0x10
	ftNotSupported            = 0x11
	ftOtherError              = 0x12
	ftDeviceListNotReady      = 0x13
	ftOpenBySerialNumber      = 0x1
	ftBits8                   = 0x8
	ftBits7                   = 0x7
	ftStopBits1               = 0x0
	ftStopBits2               = 0x2
	ftParityNone              = 0x0
	ftParityOdd               = 0x1
	ftParityEven              = 0x2
	ftFlowNone                = 0x0
	ftFlowRTSCTS              = 0x100
	ftFlowXONXOFF             = 0x400
	ftPurgeRX                 = 0x1
	ftPurgeTX                 = 0x2
	ftEventRXChar             = 0x1
	ftEventModemStatus        = 0x2
	ftModemCTS                = 0x10
	ftModemDSR                = 0x20
	ftModemRI                 = 0x40
	ftModemDCD                = 0x80
	ftDefaultRXTimeout        = 0x12c
	ftEventHandleSize         = 0x78
	ftEventCondOffset         = 0x0
	ftEventMutexOffset        = 0x30
	ftDeviceInfoNodeSize      = 0x68
	ftDeviceInfoSerialOffset  = 0x10
)

type ftDeviceListInfoNode struct {
	Flags        uint32
	Type         uint32
	ID           uint32
	LocId        uint32
	SerialNumber [16]int8
	Description  [64]int8
	FtHandle     *byte
}
