//go:build freebsd

// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types_freebsd.go

package serialenum

const (
	ctlSysctl         = 0x0
	ctlSysctlName     = 0x1
	ctlSysctlNext     = 0x2
	ctlSysctlName2oid = 0x3
)
