// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types.go

package term

type SerialICounter struct {
	Cts		int32
	Dsr		int32
	Rng		int32
	Dcd		int32
	Rx		int32
	Tx		int32
	Frame		int32
	Overrun		int32
	Parity		int32
	Brk		int32
	Buf_overrun	int32
	Reserved	[9]int32
}
