// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types.go

package unix2

type PTPClockTime struct {
	Sec		int64
	Nsec		uint32
	Reserved	uint32
}
type PTPClockCaps struct {
	Max_adj			int32
	N_alarm			int32
	N_ext_ts		int32
	N_per_out		int32
	Pps			int32
	N_pins			int32
	Cross_timestamping	int32
	Adjust_phase		int32
	Rsv			[12]int32
}

const (
	PTP_ENABLE_FEATURE	= 0x1
	PTP_RISING_EDGE		= 0x2
	PTP_FALLING_EDGE	= 0x4
	PTP_STRICT_FLAGS	= 0x8
	PTP_EXTTS_EDGES		= 0x6
)

type PTPExttsRequest struct {
	Index	uint32
	Flags	uint32
	Rsv	[2]uint32
}

const PTP_MAX_SAMPLES = 0x19

type PTPSysOffset struct {
	Samples	uint32
	Rsv	[3]uint32
	Ts	[51]PTPClockTime
}
type PTPSysOffsetExtended struct {
	Samples	uint32
	Rsv	[3]uint32
	Ts	[25][3]PTPClockTime
}
type PTPSysOffsetPrecise struct {
	Device		PTPClockTime
	Realtime	PTPClockTime
	Monoraw		PTPClockTime
	Rsv		[4]uint32
}
type PTPPeroutRequest struct {
	Start	PTPClockTime
	Period	PTPClockTime
	Index	uint32
	Flags	uint32
	On	PTPClockTime
}

const (
	PTP_PF_NONE	= 0x0
	PTP_PF_EXTTS	= 0x1
	PTP_PF_PEROUT	= 0x2
	PTP_PF_PHYSYNC	= 0x2
)

type PTPPinDesc struct {
	Name	[64]int8
	Index	uint32
	Func	uint32
	Chan	uint32
	Rsv	[5]uint32
}

type PTPExttsEvent struct {
	T	PTPClockTime
	Index	uint32
	Flags	uint32
	Rsv	[2]uint32
}

const SizeofPTPExttsEvent = 0x20

const (
	PTP_CLOCK_GETCAPS	= 0x80503d01
	PTP_EXTTS_REQUEST	= 0x40103d02
	PTP_PEROUT_REQUEST	= 0x40383d03
	PTP_ENABLE_PPS		= 0x40043d04
	PTP_SYS_OFFSET		= 0x43403d05
	PTP_PIN_GETFUNC		= 0xc0603d06
	PTP_PIN_SETFUNC		= 0x40603d07
	PTP_SYS_OFFSET_PRECISE	= 0xc0403d08
	PTP_SYS_OFFSET_EXTENDED	= 0xc4c03d09

	PTP_CLOCK_GETCAPS2		= 0x80503d0a
	PTP_EXTTS_REQUEST2		= 0x40103d0b
	PTP_PEROUT_REQUEST2		= 0x40383d0c
	PTP_ENABLE_PPS2			= 0x40043d0d
	PTP_SYS_OFFSET2			= 0x43403d0e
	PTP_PIN_GETFUNC2		= 0xc0603d0f
	PTP_PIN_SETFUNC2		= 0x40603d10
	PTP_SYS_OFFSET_PRECISE2		= 0xc0403d11
	PTP_SYS_OFFSET_EXTENDED2	= 0xc4c03d12
)

type SerialICounter struct {
	Cts		int32
	Dsr		int32
	Rng		int32
	Dcd		int32
	Rx		int32
	Tx		int32
	Frame		int32
	Overrun		int32
	Parity		int32
	Brk		int32
	Buf_overrun	int32
	Reserved	[9]int32
}

type EthtoolTsInfo struct {
	Cmd		uint32
	So_timestamping	uint32
	Phc_index	int32
	Tx_types	uint32
	Tx_reserved	[3]uint32
	Rx_filters	uint32
	Rx_reserved	[3]uint32
}

const sizeofIFreq = 0x28
