//go:build linux && (arm || 386)

// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types_linux.go

package ntpshm

type shmTime struct {
	Mode                 int32
	Count                int32
	ClockTimeStampSec    int32
	ClockTimeStampUSec   int32
	ReceiveTimeStampSec  int32
	ReceiveTimeStampUSec int32
	Leap                 int32
	Precision            int32
	Nsamples             int32
	Valid                int32
	ClockTimeStampNSec   int32
	ReceiveTimeStampNSec int32
	Dummy                [8]int32
}

const expectedSize = 0x50
