//go:build windows && (amd64 || arm64)

// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo.exe -godefs types_windows.go

package ntpshm

type shmTime struct {
	Mode                 int32
	Count                int32
	ClockTimeStampSec    int64
	ClockTimeStampUSec   int32
	ReceiveTimeStampSec  int64
	ReceiveTimeStampUSec int32
	Leap                 int32
	Precision            int32
	Nsamples             int32
	Valid                int32
	ClockTimeStampNSec   int32
	ReceiveTimeStampNSec int32
	Dummy                [8]int32
	Pad_cgo_0            [4]byte
}

const expectedSize = 0x60
