// Code generated by flicker_scale.py; DO NOT EDIT!
package clocksim

const flickerTau0 = 10.0
const flickerTauMax = 1000.0
const flickerRatio = 2.0

// Allan-weighted analytical scale factor for Kasdin-Walter filter.
const flickerAnalyticScaleFactor = 3.014399112675351

// Empirical fudge factor for discrete-time effects and approximation errors.
// Calibrated from simulator validation for τ range 10-1000s, ratio=2.0.
const flickerFudgeFactor = 0.774

// Combined scaling factor: analytic × fudge.
const flickerScaleFactor = flickerAnalyticScaleFactor * flickerFudgeFactor
