//go:build amd64 || arm64

// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types_freebsd.go

package kpps

type ppsInfo struct {
	Assert_sequence uint32
	Clear_sequence  uint32
	Assert_tu       [24]byte
	Clear_tu        [24]byte
	Current_mode    int32
	Pad_cgo_0       [4]byte
}

type ppsParams struct {
	Api_version   int32
	Mode          int32
	Assert_off_tu [24]byte
	Clear_off_tu  [24]byte
}

type ppsFetchArgs struct {
	Tsformat  int32
	Pad_cgo_0 [4]byte
	Info_buf  ppsInfo
	Timeout   timespec
}

type timespec struct {
	Sec  int64
	Nsec int64
}

const (
	ppsIocCreate    = 0x20003101
	ppsIocDestroy   = 0x20003102
	ppsIocSetParams = 0x80383103
	ppsIocGetCap    = 0x40043105
	ppsIocFetch     = 0xc0583106
	ppsAPIVers1     = 0x1
	ppsTsfmtTspec   = 0x1000
	ppsCanWait      = 0x100
)
