// Code generated by mkconsts.go; DO NOT EDIT!

package ubxcfgval

const KGpsL5HealthOverride KeyL = 0x10320001
const KHwAntCfgOpendet KeyL = 0x10a30031
const KHwAntCfgOpendetPol KeyL = 0x10a30032
const KHwAntCfgPwrdown KeyL = 0x10a30033
const KHwAntCfgPwrdownPol KeyL = 0x10a30034
const KHwAntCfgRecover KeyL = 0x10a30035
const KHwAntCfgShortdet KeyL = 0x10a3002f
const KHwAntCfgShortdetPol KeyL = 0x10a30030
const KHwAntCfgVoltctrl KeyL = 0x10a3002e
const KHwAntSupEngine KeyE[EnumHwAntSupEngine] = 0x20a30054
type EnumHwAntSupEngine uint8
const (
	EHwAntSupEngineExt EnumHwAntSupEngine = iota
	EHwAntSupEngineMadc
)
const KHwAntSupOpenPin KeyU = 0x20a30038
const KHwAntSupOpenThr KeyU = 0x20a30056
const KHwAntSupShortPin KeyU = 0x20a30037
const KHwAntSupShortThr KeyU = 0x20a30055
const KHwAntSupSwitchPin KeyU = 0x20a30036
const KHwRfLnaMode KeyE[EnumHwRfLnaMode] = 0x20a30057
type EnumHwRfLnaMode uint8
const (
	EHwRfLnaModeNormal EnumHwRfLnaMode = iota
	EHwRfLnaModeLowgain
	EHwRfLnaModeBypass
)
const KNavspgAckaiding KeyL = 0x10110025
const KNavspgConstrAlt KeyI = 0x401100c1
const KNavspgConstrAltvar KeyU = 0x401100c2
const KNavspgConstrDgnssto KeyU = 0x201100c4
const KNavspgDynmodel KeyE[EnumNavspgDynmodel] = 0x20110021
type EnumNavspgDynmodel uint8
const (
	ENavspgDynmodelPort EnumNavspgDynmodel = iota
	_
	ENavspgDynmodelStat
	ENavspgDynmodelPed
	ENavspgDynmodelAutomot
	ENavspgDynmodelSea
	ENavspgDynmodelAir1
	ENavspgDynmodelAir2
	ENavspgDynmodelAir4
	ENavspgDynmodelWrist
	ENavspgDynmodelBike
	ENavspgDynmodelMower
	ENavspgDynmodelEscooter
)
const KNavspgFixmode KeyE[EnumNavspgFixmode] = 0x20110011
type EnumNavspgFixmode uint8
const (
	_ EnumNavspgFixmode = iota
	ENavspgFixmode2donly
	ENavspgFixmode3donly
	ENavspgFixmodeAuto
)
const KNavspgInfilCnothrs KeyU = 0x201100ab
const KNavspgInfilMaxsvs KeyU = 0x201100a2
const KNavspgInfilMincno KeyU = 0x201100a3
const KNavspgInfilMinelev KeyI = 0x201100a4
const KNavspgInfilMinsvs KeyU = 0x201100a1
const KNavspgInfilNcnothrs KeyU = 0x201100aa
const KNavspgInifix3d KeyL = 0x10110013
const KNavspgOutfilFacc KeyU = 0x301100b5
const KNavspgOutfilPacc KeyU = 0x301100b3
const KNavspgOutfilPdop KeyU = 0x301100b1
const KNavspgOutfilTacc KeyU = 0x301100b4
const KNavspgOutfilTdop KeyU = 0x301100b2
const KNavspgSigattcomp KeyE[EnumNavspgSigattcomp] = 0x201100d6
type EnumNavspgSigattcomp uint8
const (
	ENavspgSigattcompDis EnumNavspgSigattcomp = iota
	ENavspgSigattcomp01dbhz
	ENavspgSigattcomp02dbhz
	ENavspgSigattcomp03dbhz
	ENavspgSigattcomp04dbhz
	ENavspgSigattcomp05dbhz
	ENavspgSigattcomp06dbhz
	ENavspgSigattcomp07dbhz
	ENavspgSigattcomp08dbhz
	ENavspgSigattcomp09dbhz
	ENavspgSigattcomp10dbhz
	ENavspgSigattcomp11dbhz
	ENavspgSigattcomp12dbhz
	ENavspgSigattcomp13dbhz
	ENavspgSigattcomp14dbhz
	ENavspgSigattcomp15dbhz
	ENavspgSigattcomp16dbhz
	ENavspgSigattcomp17dbhz
	ENavspgSigattcomp18dbhz
	ENavspgSigattcomp19dbhz
	ENavspgSigattcomp20dbhz
	ENavspgSigattcomp21dbhz
	ENavspgSigattcomp22dbhz
	ENavspgSigattcomp23dbhz
	ENavspgSigattcomp24dbhz
	ENavspgSigattcomp25dbhz
	ENavspgSigattcomp26dbhz
	ENavspgSigattcomp27dbhz
	ENavspgSigattcomp28dbhz
	ENavspgSigattcomp29dbhz
	ENavspgSigattcomp30dbhz
	ENavspgSigattcomp31dbhz
	ENavspgSigattcomp32dbhz
	ENavspgSigattcomp33dbhz
	ENavspgSigattcomp34dbhz
	ENavspgSigattcomp35dbhz
	ENavspgSigattcomp36dbhz
	ENavspgSigattcomp37dbhz
	ENavspgSigattcomp38dbhz
	ENavspgSigattcomp39dbhz
	ENavspgSigattcomp40dbhz
	ENavspgSigattcomp41dbhz
	ENavspgSigattcomp42dbhz
	ENavspgSigattcomp43dbhz
	ENavspgSigattcomp44dbhz
	ENavspgSigattcomp45dbhz
	ENavspgSigattcomp46dbhz
	ENavspgSigattcomp47dbhz
	ENavspgSigattcomp48dbhz
	ENavspgSigattcomp49dbhz
	ENavspgSigattcomp50dbhz
	ENavspgSigattcomp51dbhz
	ENavspgSigattcomp52dbhz
	ENavspgSigattcomp53dbhz
	ENavspgSigattcomp54dbhz
	ENavspgSigattcomp55dbhz
	ENavspgSigattcomp56dbhz
	ENavspgSigattcomp57dbhz
	ENavspgSigattcomp58dbhz
	ENavspgSigattcomp59dbhz
	ENavspgSigattcomp60dbhz
	ENavspgSigattcomp61dbhz
	ENavspgSigattcomp62dbhz
	ENavspgSigattcomp63dbhz
	ENavspgSigattcompAuto EnumNavspgSigattcomp = 255
)
const KNavspgUseUsrdat KeyL = 0x10110061
const KNavspgUsrdatDx KeyR = 0x40110064
const KNavspgUsrdatDy KeyR = 0x40110065
const KNavspgUsrdatDz KeyR = 0x40110066
const KNavspgUsrdatFlat KeyR = 0x50110063
const KNavspgUsrdatMaja KeyR = 0x50110062
const KNavspgUsrdatRotx KeyR = 0x40110067
const KNavspgUsrdatRoty KeyR = 0x40110068
const KNavspgUsrdatRotz KeyR = 0x40110069
const KNavspgUsrdatScale KeyR = 0x4011006a
const KNavspgUtcstandard KeyE[EnumNavspgUtcstandard] = 0x2011001c
type EnumNavspgUtcstandard uint8
const (
	ENavspgUtcstandardAuto EnumNavspgUtcstandard = iota
	_
	_
	ENavspgUtcstandardUsno
	_
	ENavspgUtcstandardEu
	ENavspgUtcstandardSu
	ENavspgUtcstandardNtsc
	ENavspgUtcstandardNpli
	ENavspgUtcstandardNict
)
const KNavspgWknrollover KeyU = 0x30110017
const KRateMeas KeyU = 0x30210001
const KRateNav KeyU = 0x30210002
const KRateTimeref KeyE[EnumRateTimeref] = 0x20210003
type EnumRateTimeref uint8
const (
	ERateTimerefUtc EnumRateTimeref = iota
	ERateTimerefGps
	ERateTimerefGlo
	ERateTimerefBds
	ERateTimerefGal
)
const KSignalBdsB1Ena KeyL = 0x1031000d
const KSignalBdsB1cEna KeyL = 0x1031000f
const KSignalBdsB2Ena KeyL = 0x1031000e
const KSignalBdsB2aEna KeyL = 0x10310028
const KSignalBdsEna KeyL = 0x10310022
const KSignalGalE1Ena KeyL = 0x10310007
const KSignalGalE5aEna KeyL = 0x10310009
const KSignalGalE5bEna KeyL = 0x1031000a
const KSignalGalEna KeyL = 0x10310021
const KSignalGloEna KeyL = 0x10310025
const KSignalGloL1Ena KeyL = 0x10310018
const KSignalGloL2Ena KeyL = 0x1031001a
const KSignalGpsEna KeyL = 0x1031001f
const KSignalGpsL1caEna KeyL = 0x10310001
const KSignalGpsL2cEna KeyL = 0x10310003
const KSignalGpsL5Ena KeyL = 0x10310004
const KSignalNavicEna KeyL = 0x10310026
const KSignalNavicL5Ena KeyL = 0x1031001d
const KSignalQzssEna KeyL = 0x10310024
const KSignalQzssL1caEna KeyL = 0x10310012
const KSignalQzssL1sEna KeyL = 0x10310014
const KSignalQzssL2cEna KeyL = 0x10310015
const KSignalQzssL5Ena KeyL = 0x10310017
const KSignalSbasEna KeyL = 0x10310020
const KSignalSbasL1caEna KeyL = 0x10310005
const KTmodeEcefX KeyI = 0x40030003
const KTmodeEcefXHp KeyI = 0x20030006
const KTmodeEcefY KeyI = 0x40030004
const KTmodeEcefYHp KeyI = 0x20030007
const KTmodeEcefZ KeyI = 0x40030005
const KTmodeEcefZHp KeyI = 0x20030008
const KTmodeFixedPosAcc KeyU = 0x4003000f
const KTmodeHeight KeyI = 0x4003000b
const KTmodeHeightHp KeyI = 0x2003000e
const KTmodeLat KeyI = 0x40030009
const KTmodeLatHp KeyI = 0x2003000c
const KTmodeLon KeyI = 0x4003000a
const KTmodeLonHp KeyI = 0x2003000d
const KTmodeMode KeyE[EnumTmodeMode] = 0x20030001
type EnumTmodeMode uint8
const (
	ETmodeModeDisabled EnumTmodeMode = iota
	ETmodeModeSurveyIn
	ETmodeModeFixed
)
const KTmodePosType KeyE[EnumTmodePosType] = 0x20030002
type EnumTmodePosType uint8
const (
	ETmodePosTypeEcef EnumTmodePosType = iota
	ETmodePosTypeLlh
)
const KTmodeSvinAccLimit KeyU = 0x40030011
const KTmodeSvinMinDur KeyU = 0x40030010
const KTpAlignToTowTp1 KeyL = 0x1005000a
const KTpAlignToTowTp2 KeyL = 0x10050015
const KTpAntCabledelay KeyI = 0x30050001
const KTpDrstrTp1 KeyE[EnumTpDrstrTp1] = 0x20050035
type EnumTpDrstrTp1 uint8
const (
	ETpDrstrTp1DriveStrength2ma EnumTpDrstrTp1 = iota
	ETpDrstrTp1DriveStrength4ma
	ETpDrstrTp1DriveStrength8ma
	ETpDrstrTp1DriveStrength12ma
)
const KTpDrstrTp2 KeyE[EnumTpDrstrTp2] = 0x20050036
type EnumTpDrstrTp2 uint8
const (
	ETpDrstrTp2DriveStrength2ma EnumTpDrstrTp2 = iota
	ETpDrstrTp2DriveStrength4ma
	ETpDrstrTp2DriveStrength8ma
	ETpDrstrTp2DriveStrength12ma
)
const KTpDutyLockTp1 KeyR = 0x5005002b
const KTpDutyLockTp2 KeyR = 0x5005002d
const KTpDutyTp1 KeyR = 0x5005002a
const KTpDutyTp2 KeyR = 0x5005002c
const KTpFreqLockTp1 KeyU = 0x40050025
const KTpFreqLockTp2 KeyU = 0x40050027
const KTpFreqTp1 KeyU = 0x40050024
const KTpFreqTp2 KeyU = 0x40050026
const KTpLenLockTp1 KeyU = 0x40050005
const KTpLenLockTp2 KeyU = 0x40050010
const KTpLenTp1 KeyU = 0x40050004
const KTpLenTp2 KeyU = 0x4005000f
const KTpPeriodLockTp1 KeyU = 0x40050003
const KTpPeriodLockTp2 KeyU = 0x4005000e
const KTpPeriodTp1 KeyU = 0x40050002
const KTpPeriodTp2 KeyU = 0x4005000d
const KTpPolTp1 KeyL = 0x1005000b
const KTpPolTp2 KeyL = 0x10050016
const KTpPulseDef KeyE[EnumTpPulseDef] = 0x20050023
type EnumTpPulseDef uint8
const (
	ETpPulseDefPeriod EnumTpPulseDef = iota
	ETpPulseDefFreq
)
const KTpPulseLengthDef KeyE[EnumTpPulseLengthDef] = 0x20050030
type EnumTpPulseLengthDef uint8
const (
	ETpPulseLengthDefRatio EnumTpPulseLengthDef = iota
	ETpPulseLengthDefLength
)
const KTpSyncGnssTp1 KeyL = 0x10050008
const KTpSyncGnssTp2 KeyL = 0x10050013
const KTpTimegridTp1 KeyE[EnumTpTimegridTp1] = 0x2005000c
type EnumTpTimegridTp1 uint8
const (
	ETpTimegridTp1Utc EnumTpTimegridTp1 = iota
	ETpTimegridTp1Gps
	ETpTimegridTp1Glo
	ETpTimegridTp1Bds
	ETpTimegridTp1Gal
	ETpTimegridTp1Navic
)
const KTpTimegridTp2 KeyE[EnumTpTimegridTp2] = 0x20050017
type EnumTpTimegridTp2 uint8
const (
	ETpTimegridTp2Utc EnumTpTimegridTp2 = iota
	ETpTimegridTp2Gps
	ETpTimegridTp2Glo
	ETpTimegridTp2Bds
	ETpTimegridTp2Gal
	ETpTimegridTp2Navic
)
const KTpTp1Ena KeyL = 0x10050007
const KTpTp2Ena KeyL = 0x10050012
const KTpUseLockedTp1 KeyL = 0x10050009
const KTpUseLockedTp2 KeyL = 0x10050014
const KTpUserDelayTp1 KeyI = 0x40050006
const KTpUserDelayTp2 KeyI = 0x40050011
const KUart1Baudrate KeyU = 0x40520001
const KUart1Databits KeyE[EnumUart1Databits] = 0x20520003
type EnumUart1Databits uint8
const (
	EUart1DatabitsEight EnumUart1Databits = iota
	EUart1DatabitsSeven
)
const KUart1Enabled KeyL = 0x10520005
const KUart1Parity KeyE[EnumUart1Parity] = 0x20520004
type EnumUart1Parity uint8
const (
	EUart1ParityNone EnumUart1Parity = iota
	EUart1ParityOdd
	EUart1ParityEven
)
const KUart1Stopbits KeyE[EnumUart1Stopbits] = 0x20520002
type EnumUart1Stopbits uint8
const (
	EUart1StopbitsHalf EnumUart1Stopbits = iota
	EUart1StopbitsOne
	EUart1StopbitsOnehalf
	EUart1StopbitsTwo
)
const KUart1inprotNmea KeyL = 0x10730002
const KUart1inprotRtcm3x KeyL = 0x10730004
const KUart1inprotUbx KeyL = 0x10730001
const KUart1outprotNmea KeyL = 0x10740002
const KUart1outprotRtcm3x KeyL = 0x10740004
const KUart1outprotUbx KeyL = 0x10740001
const KUart2Baudrate KeyU = 0x40530001
const KUart2Databits KeyE[EnumUart2Databits] = 0x20530003
type EnumUart2Databits uint8
const (
	EUart2DatabitsEight EnumUart2Databits = iota
	EUart2DatabitsSeven
)
const KUart2Enabled KeyL = 0x10530005
const KUart2Parity KeyE[EnumUart2Parity] = 0x20530004
type EnumUart2Parity uint8
const (
	EUart2ParityNone EnumUart2Parity = iota
	EUart2ParityOdd
	EUart2ParityEven
)
const KUart2Stopbits KeyE[EnumUart2Stopbits] = 0x20530002
type EnumUart2Stopbits uint8
const (
	EUart2StopbitsHalf EnumUart2Stopbits = iota
	EUart2StopbitsOne
	EUart2StopbitsOnehalf
	EUart2StopbitsTwo
)
const KUart2inprotNmea KeyL = 0x10750002
const KUart2inprotRtcm3x KeyL = 0x10750004
const KUart2inprotUbx KeyL = 0x10750001
const KUart2outprotNmea KeyL = 0x10760002
const KUart2outprotRtcm3x KeyL = 0x10760004
const KUart2outprotUbx KeyL = 0x10760001
const KUsbinprotNmea KeyL = 0x10770002
const KUsbinprotRtcm3x KeyL = 0x10770004
const KUsbinprotUbx KeyL = 0x10770001
const KUsboutprotNmea KeyL = 0x10780002
const KUsboutprotRtcm3x KeyL = 0x10780004
const KUsboutprotUbx KeyL = 0x10780001
