//go:build ignore
// +build ignore

package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/jclark/gps4ptp/internal/ubxcfgval/cfgschema"
)

func main() {
	bytes, err := os.ReadFile("cfgschema/cfg.yaml")
	if err == nil {
		schema, err := cfgschema.UnmarshalYAML(bytes)
		if err == nil {
			err = os.WriteFile("consts.go", []byte(fmtSchema(schema)), 0644)
		}
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "%s: %v\n", os.Args[0], err)
		os.Exit(1)
	}
}

func fmtSchema(schema map[string]map[string]cfgschema.Item) string {
	lines := make([]string, 0)
	for grpName, m := range schema {
		for name, item := range m {
			lines = append(lines, fmtItem(grpName, name, item))
		}
	}
	sort.Strings(lines)
	return fmt.Sprintf("// Code generated by mkconsts.go; DO NOT EDIT!\n\npackage ubxcfgval\n\n%s\n", strings.Join(lines, "\n"))
}

func fmtItem(grpName string, name string, item cfgschema.Item) string {
	typeName, typeDef := fmtType(grpName, name, item.Type, item.Constants)
	return fmt.Sprintf("const %s %s = 0x%x%s", constName(grpName, name), typeName, item.Key, typeDef)
}

func constName(grpName string, name string) string {
	return "K" + camelCase(grpName+"_"+name)
}

func camelCase(s string) string {
	words := strings.Split(s, "_")
	for i, w := range words {
		words[i] = strings.ToUpper(w[:1]) + strings.ToLower(w[1:])
	}
	return strings.Join(words, "")
}

const maxUnderscore = 3

func fmtType(grpName, name string, typ string, cMap map[string]cfgschema.Constant) (string, string) {
	if typ != "E1" || cMap == nil {
		return "Key" + typ[:1], ""
	}
	baseName := camelCase(grpName + "_" + name)
	enumType := "Enum" + baseName
	consts := constsArray(cMap)
	code := ""
	skipped := 0
	defaultOK := true
	for i, s := range consts {
		id := s
		if id == "" {
			if i != 0 {
				skipped++
				continue
			}
			id = "_"
		} else {
			id = "E" + baseName + camelCase(id)
		}
		if i == 0 {
			code = fmt.Sprintf("\t%s %s = iota\n", id, enumType)
		} else if defaultOK && skipped <= maxUnderscore {
			code += fmt.Sprintf("%s\t%s\n", strings.Repeat("\t_\n", skipped), id)
			skipped = 0
		} else {
			code += fmt.Sprintf("\t%s %s = %d\n", id, enumType, i)
			defaultOK = false
		}
	}
	return fmt.Sprintf("KeyE[%s]", enumType), fmt.Sprintf("\ntype %s uint8\nconst (\n%s)", enumType, code)
}

func constsArray(cMap map[string]cfgschema.Constant) []string {
	n := uint64(0)
	for _, c := range cMap {
		i := c.Value
		if i >= n {
			n = i + 1
		}
	}
	consts := make([]string, n)
	for s, c := range cMap {
		consts[c.Value] = s
	}
	return consts
}
