// Code generated by "stringer -type=GNSS"; DO NOT EDIT.

package gpsmsg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GPS-1]
	_ = x[GAL-2]
	_ = x[BDS-3]
	_ = x[GLO-4]
	_ = x[NAVIC-5]
	_ = x[QZSS-6]
	_ = x[SBAS-7]
}

const _GNSS_name = "GPSGALBDSGLONAVICQZSSSBAS"

var _GNSS_index = [...]uint8{0, 3, 6, 9, 12, 17, 21, 25}

func (i GNSS) String() string {
	i -= 1
	if i < 0 || i >= GNSS(len(_GNSS_index)-1) {
		return "GNSS(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _GNSS_name[_GNSS_index[i]:_GNSS_index[i+1]]
}
