// Package latin1z provides fixed-size byte-array types whose contents are
// interpreted as nul-terminated ISO 8859-1 (Latin-1) strings. Each typed
// array has String and MarshalJSON methods that decode the bytes up to the
// first nul as a Latin-1 string.
//
// The typed arrays (StringZ5, StringZ10, ...) are generated by mksizes.go.
package latin1z

//go:generate go run mksizes.go

// ToString decodes a nul-terminated ISO 8859-1 (Latin-1) byte slice into a
// string, stopping at the first nul byte. Each byte is mapped to the Unicode
// code point with the same numeric value.
func ToString(b []byte) string {
	r := make([]rune, 0, len(b))
	for _, c := range b {
		if c == 0 {
			break
		}
		r = append(r, rune(c))
	}
	return string(r)
}
