//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
)

// sizes lists the array lengths to generate StringZN types for.
// Add a new size here when a new message type needs it, then re-run
// `go generate ./...`.
var sizes = []int{5, 10, 16, 30, 32, 33, 43, 66, 129}

func main() {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by mksizes.go; DO NOT EDIT.\n\n")
	buf.WriteString("package latin1z\n\n")
	buf.WriteString("import \"encoding/json\"\n\n")
	for _, n := range sizes {
		fmt.Fprintf(&buf, "// StringZ%d is a [%d]byte holding a nul-terminated Latin-1 string.\n", n, n)
		fmt.Fprintf(&buf, "type StringZ%d [%d]byte\n\n", n, n)
		fmt.Fprintf(&buf, "func (z StringZ%d) String() string { return ToString(z[:]) }\n", n)
		fmt.Fprintf(&buf, "func (z StringZ%d) MarshalJSON() ([]byte, error) { return json.Marshal(z.String()) }\n\n", n)
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "%s: format: %v\n", os.Args[0], err)
		os.Exit(1)
	}
	if err := os.WriteFile("sizes.go", src, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "%s: %v\n", os.Args[0], err)
		os.Exit(1)
	}
}
