// Package ts provides TypeScript type definitions for GPS JSON serialisation.
// See README.md for details.
//
//go:generate go run gen.go
package ts

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"

	"github.com/jclark/satpulse/gps/app/gpsio"
	"github.com/jclark/satpulse/gps/gpsprot"
	"github.com/jclark/satpulse/gps/lib/opt"
	"github.com/jclark/satpulse/gps/ptime"
)

type sample struct {
	tsType string
	value  any
}

func samples() []sample {
	pulseOff := 0.000000125
	speed := 9600
	return []sample{
		{"SatellitesMsg", gpsprot.SatellitesMsg{
			Tag:         "UBX",
			NativeMsgID: "NAV-SAT",
			SVs: []gpsprot.SVInfo{
				{
					ID:         gpsprot.SVID{GNSS: gpsprot.GPS, Num: 1},
					LookAngles: &gpsprot.LookAngles{Azimuth: 45, Elevation: 30},
					Signals:    []gpsprot.SignalInfo{{ID: "L1 C/A", CN0: 42, Used: true}},
					Used:       true,
				},
			},
			UsedValidity: gpsprot.SatelliteUsedSignal,
		}},
		{"TimeMsg", gpsprot.TimeMsg{
			TAITime:     ptime.Time(1741320000 * 1e9),
			UTCTime:     utcTime(2025, 3, 7, 4, 0, 0),
			Accuracy:    25 * time.Millisecond,
			UTCOffset:   37,
			PulseOffset: &pulseOff,
			GNSS:        gpsprot.GPS,
			Ref:         gpsprot.NavSolution,
			Tag:         "UBX",
			NativeMsgID: "NAV-TIMEGPS",
		}},
		{"SurveyMsg", gpsprot.SurveyMsg{
			Position:   gpsprot.Point3D{4075539814000, 555132076000, 4828427312000},
			Accuracy:   25000,
			ObsCount:   3600,
			ObsTime:    gpsprot.Duration(3600 * time.Second),
			Valid:      true,
			InProgress: false,
		}},
		{"PosGeoMsg", gpsprot.PosGeoMsg{
			LatLon:      [2]gpsprot.Angle{gpsprot.DegreesFromFloat(51.477928), gpsprot.DegreesFromFloat(-0.001545)},
			Height:      opt.Make(gpsprot.Length(45321000)),
			HeightMSL:   opt.Make(gpsprot.Length(0)),
			Tag:         "UBX",
			NativeMsgID: "NAV-PVT",
		}},
		{"PosECEFMsg", gpsprot.PosECEFMsg{
			Pos:         gpsprot.Point3D{4075539814000, 555132076000, 4828427312000},
			Tag:         "UBX",
			NativeMsgID: "NAV-PVT",
		}},
		{"VelGeoMsg", gpsprot.VelGeoMsg{
			VelNED:      opt.Make([3]gpsprot.Speed{15000, -3000, 1000}),
			GroundSpeed: opt.Make(gpsprot.Speed(15000)),
			Speed3D:     opt.Make(gpsprot.Speed(16000)),
			Course:      opt.Make(gpsprot.DegreesFromFloat(78.5)),
			Tag:         "UBX",
			NativeMsgID: "NAV-PVT",
		}},
		{"VelECEFMsg", gpsprot.VelECEFMsg{
			Vel:         [3]gpsprot.Speed{12000, -5000, 3000},
			Tag:         "UBX",
			NativeMsgID: "NAV-PVT",
		}},
		{"PVMsgBundle", gpsprot.PVMsgBundle{
			PosGeo: opt.Make(gpsprot.PosGeoMsg{
				LatLon:      [2]gpsprot.Angle{gpsprot.DegreesFromFloat(51.477928), gpsprot.DegreesFromFloat(-0.001545)},
				Tag:         "UBX",
				NativeMsgID: "NAV-PVT",
			}),
			VelECEF: opt.Make(gpsprot.VelECEFMsg{
				Vel:         [3]gpsprot.Speed{12000, -5000, 3000},
				Tag:         "UBX",
				NativeMsgID: "NAV-PVT",
			}),
		}},
		{"NavEpochMsg", gpsprot.NavEpochMsg{
			FixLevel:    gpsprot.FixLevelCarrierFixed,
			SolutionDim: gpsprot.SolutionDim3D,
			Correction:  gpsprot.CorrRTCM,
			Acc:         gpsprot.Accuracy{Hor: opt.Make(gpsprot.Length(15000)), Vert: opt.Make(gpsprot.Length(25000))},
			DOP:         gpsprot.DOP{Pos: opt.Make(1.2), Hor: opt.Make(0.8)},
			NumSVUsed:   opt.Make[uint16](12),
			SignalsUsed: gpsprot.SignalSetOf(gpsprot.SigGPSL1CA, gpsprot.SigGPSL5, gpsprot.SigGALE1),
			Tag:         "UBX",
			StartTime:   time.Date(2025, 3, 7, 4, 0, 0, 0, time.UTC),
		}},
		{"LeapSecondMsg", gpsprot.LeapSecondMsg{
			LeapSecond: ptime.LeapSecond{
				OffChangeTime: ptime.Time(1735689637 * 1e9),
				UTCOffBefore:  37,
				UTCOffAfter:   37,
			},
			GNSS: gpsprot.GPS,
		}},
		{"ReceiverInfo", gpsprot.ReceiverInfo{
			Vendor:        "u-blox",
			Firmware:      "TIM 2.20 PROTVER 18.00",
			Hardware:      "ZED-F9T",
			SupportedGNSS: 1<<gpsprot.GPS | 1<<gpsprot.GAL | 1<<gpsprot.BDS | 1<<gpsprot.GLO,
		}},
		{"PacketLogEntry", gpsio.PacketLogEntry{
			T:     gpsio.TimeMicro(time.Date(2025, 3, 7, 4, 0, 0, 123456000, time.UTC)),
			Tag:   "UBX",
			Msg:   "NAV-PVT",
			Bin:   gpsio.HexString{0xb5, 0x62, 0x01, 0x07},
			Speed: &speed,
			Out:   false,
		}},
	}
}

// Generate produces the contents of validate.gen.ts.
func Generate() ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	buf.WriteString("import type {")
	gpsprots := []string{
		"SatellitesMsg", "TimeMsg", "SurveyMsg",
		"PosGeoMsg", "PosECEFMsg", "VelGeoMsg", "VelECEFMsg", "PVMsgBundle",
		"NavEpochMsg", "LeapSecondMsg", "ReceiverInfo",
	}
	for i, name := range gpsprots {
		if i > 0 {
			buf.WriteString(",")
		}
		buf.WriteString(" " + name)
	}
	buf.WriteString("} from './gpsprot';\n")
	buf.WriteString("import type {PacketLogEntry} from './gpsio';\n")
	buf.WriteString("\n")
	for _, s := range samples() {
		j, err := json.Marshal(s.value)
		if err != nil {
			return nil, fmt.Errorf("marshal %s: %w", s.tsType, err)
		}
		fmt.Fprintf(&buf, "const _%s: %s = %s;\n", lcFirst(s.tsType), s.tsType, j)
	}
	return buf.Bytes(), nil
}

func lcFirst(s string) string {
	if s == "" {
		return s
	}
	return string(s[0]|0x20) + s[1:]
}

func utcTime(year int, month time.Month, day, hour, min, sec int) *ptime.UTCTime {
	date := time.Date(year, month, day, 0, 0, 0, 0, time.UTC)
	tod := time.Duration(hour)*time.Hour + time.Duration(min)*time.Minute + time.Duration(sec)*time.Second
	return &ptime.UTCTime{Date: date, TimeOfDay: tod}
}
