# This chrony refclock line would be used in conjunction with satpulse with the following config
# [ntp]
# sock.path = "/var/run/chrony.satpulse.sock"
refclock SOCK /var/run/chrony.satpulse.sock poll 2 filter 4 refid GNSS
