# Example of how to generate chrony SOCK refclock samples
# chrony.conf would need a line like:
# refclock SOCK /var/run/chrony.satpulse.sock poll 2 filter 4 refid GNSS
[ntp]
sock.path = "/var/run/chrony.satpulse.sock"
