# Config file for satpulse on the Raspberry Pi CM4
[serial]
device = "/dev/ttyAMA0"
speed = 9600

[phc]
interface = "eth0"

[ptp]
# Change to "none" to prevent doing updates
impl = "ptp4l"
# Unix domain socket for PTP management
# Same as ptp4l udsAddress config option
udsAddress = "/var/run/ptp4l"
domainNumber = 0
# This corresponds to ptp4l transportSpecific option
# (It's called majorSdoId in latest version of PTP standard.) 
majorSdoId = 0

# Uncomment this to have it relay the GPS serial port to a TCP connection
#[[tcp]]
#listen = ":2006"
#readOnly = true
