# Config file for satpulse on the Raspberry Pi CM4
[serial]
device = "/dev/ttyAMA0"
speed = 9600

[phc]
interface = "eth0"

[ptp]
# Unix domain socket for PTP management
# Corresponds to ptp4l uds_address config option
# Comment this out to stop satpulse updating ptp4l
ptp4l.udsAddress = "/var/run/ptp4l"
# PTP domain number
domainNumber = 0
# This corresponds to ptp4l transportSpecific option
# (It's called majorSdoId in latest version of PTP standard.) 
majorSdoId = 0

# Uncomment this to allow a TCP connection to proxy the serial port
#[[proxy.tcp]]
#listen = ":2006"
#readOnly = true

[ntp]
# Uncomment the sock.path line to act as a refclock SOCK for chrony
# chrony.conf would need a line like:
# refclock SOCK /var/run/chrony.satpulse.sock poll 2 filter 4 refid GNSS
#sock.path = "/var/run/chrony.satpulse.sock"
