# Config file for satpulse
[serial]
# This can be overridden with the -d option on the command-line
device = "/dev/ttyUSB0"
speed = 9600

[phc]
interface = "enp1s0"
channel = 0
pin = 0

[ptp]
# Change to "none" to prevent doing updates
impl = "ptp4l"
# Unix domain socket for PTP management
# Same as ptp4l udsAddress config option
udsAddress = "/var/run/ptp4l"
domainNumber = 0
# This corresponds to ptp4l transportSpecific option
# (It's called majorSdoId in latest version of PTP standard.) 
majorSdoId = 0

# Uncomment this to allow a TCP connection to proxy the serial port
#[[proxy.tcp]]
#listen = ":2006"
#readOnly = true
