# Example TCP configuration for satpulse.
[serial]
# This can be overridden with the -d option on the command-line
device = "/dev/ttyACM0"
speed = 9600

[phc]
interface = "enp1s0"

# This section allows HTTP monitoring on port 2000
[[http]]
listen = ":2000"

