# Example ptp4l configuration file for use with satpulse.
# This should be installed as
#  /etc/linuxptp/ptp4l.conf (on Debian-based distributions)
#  /etc/ptp4l.conf (on RedHat-based distributions)
# Most configuration options can be left with their default values.
# You can find configurations for particular profiles in /usr/share/doc/linuxptp/configs

[global]
# We don't want ptp4l and satpulse to both adjust the PHC, so only run as a master.
masterOnly 1
# Since we we are always running as a master, we don't need to run the BMCA to figure out our role.
BMCA noop
# satpulse will set the clock quality properties once the PHC is synchronized to the GPS,
# so the initial values should be appropriate for the non-synchronized state.
# This clock class means that it was previously synchronized to a GPS, but is now outside the holdover specification.
clockClass 52

# Uncomment this for rPI CM4
# tx_timestamp_timeout 100
