#:schema ./config-schema.json
# Default config file for satpulse
[phc]
interface = "enp1s0"
channel = 0
pin = 0

[serial]
# This can be overridden with the -d option on the command-line
device = "/dev/ttyUSB0"
speed = 9600

[gps]
# Uncommenting the following line will enable configuration of the GPS
# (changes are not persistent across GPS reboots)
#config = true
# This gives the scheme used for non-standard numbering of space vehicles in NMEA GSV and GSA sentences.
# This is needed to show all satellites in the satellites view, particularly when GPS receivers
# are using versions of NMEA before 4.11.
# Possible values are "u-blox" and "allystar". Default is not to include satellites with non-standard numbers.
#nmeaNumbering = "u-blox"

[log]
# Uncomment the following line to enable logging of PHC offsets (in /var/log/satpulse/)
# clock = true

[ptp]
# Unix domain socket for PTP management
# Corresponds to ptp4l uds_address config option
# Comment this out to stop satpulse updating ptp4l
ptp4l.udsAddress = "/var/run/ptp4l"
# PTP domain number
domainNumber = 0
# This corresponds to ptp4l transportSpecific option
# (It's called majorSdoId in latest version of PTP standard.) 
majorSdoId = 0
# Maximum of absolute value of offset in nanoseconds between PHC and GPS when in sync.
# The offsets are smoothed, so it is OK if this is exceeded occasionally.
# It will be rounded up to the next value supported by PTP (e.g. 10, 25, 100, 250, 1000)
# and set as the clockAccuracy attribute of the PTP instance.
# 150 is conservative. With a good GPS and sky view, 60 should be achievable
# (rounding up to clockAccuracy of 100ns).
clockAccuracy = 150

[ntp]
# Uncomment the sock.path line to act as a refclock SOCK for chrony
# chrony.conf would need a line like:
# refclock SOCK /var/run/chrony.satpulse.sock poll 2 filter 4 refid GNSS
#sock.path = "/var/run/chrony.satpulse.sock"

# Uncomment the following two lines to allow HTTP monitoring on port 2000
#[[http]]
#listen = ":2000"

# Uncomment this to allow a TCP connection to proxy the serial port
#[[proxy.tcp]]
#listen = ":2006"
#readOnly = true

# Uncomment this to allow a Unix domain socket to proxy the serial port
# This can be used with
#    satpulsetool gps --socket /var/run/satpulse.sock
#[[proxy.socket]]
#path = "/var/run/satpulse.sock"
