# Config file for satpulse
[phc]
interface = "enp1s0"
channel = 0
pin = 0

[serial]
# This can be overridden with the -d option on the command-line
device = "/dev/ttyUSB0"
speed = 9600

[ptp]
# Unix domain socket for PTP management
# Corresponds to ptp4l uds_address config option
# Comment this out to stop satpulse updating ptp4l
ptp4l.udsAddress = "/var/run/ptp4l"
# PTP domain number
domainNumber = 0
# This corresponds to ptp4l transportSpecific option
# (It's called majorSdoId in latest version of PTP standard.) 
majorSdoId = 0

[ntp]
# Uncomment the sock.path line to act as a refclock SOCK for chrony
# chrony.conf would need a line like:
# refclock SOCK /var/run/chrony.satpulse.sock poll 2 filter 4 refid GNSS
#sock.path = "/var/run/chrony.satpulse.sock"

# Uncomment this to allow a TCP connection to proxy the serial port
#[[proxy.tcp]]
#listen = ":2006"
#readOnly = true

# Uncomment this to allow a Unix domain socket to proxy the serial port
# This can be used with
#    satpulsetool gps --socket /var/run/satpulse.sock
#[[proxy.socket]]
#path = "/var/run/satpulse.sock"
