//go:build windows

// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo.exe -godefs types_windows.go

package timeprov

type pipeSample struct {
	Magic      uint32
	Leap       uint8
	Reserved   [3]uint8
	SysTime    uint64
	Offset     int64
	Dispersion uint64
}

const (
	recSize  = 0x20
	recMagic = 0x31565054
)
