// Code generated by "stringer -type=TimeRef"; DO NOT EDIT.

package gpsprot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NavSolution-0]
	_ = x[PrePulse-1]
	_ = x[PostPulse-2]
}

const _TimeRef_name = "NavSolutionPrePulsePostPulse"

var _TimeRef_index = [...]uint8{0, 11, 19, 28}

func (i TimeRef) String() string {
	if i < 0 || i >= TimeRef(len(_TimeRef_index)-1) {
		return "TimeRef(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TimeRef_name[_TimeRef_index[i]:_TimeRef_index[i+1]]
}
