# Build and test the GPS tree for js/wasm using Node.js.

name: Build (js/wasm)

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.26.x'

    - name: Test GPS packages
      env:
        GOOS: js
        GOARCH: wasm
      run: PATH="$PATH:$(go env GOROOT)/lib/wasm" go test ./gps/...
