# This workflow builds satpulsetool on macOS with make
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build (macOS)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.x'

    - name: Install pandoc
      run: brew install pandoc

    - name: Build
      run: make bin man

    - name: Build find-serial
      run: make -C macos OUTDIR=../out/darwin_arm64

    - name: Run find-serial (list mode)
      run: out/darwin_arm64/find-serial

    - name: Test
      run: make test

    - name: Install
      run: make install-bin install-man prefix=${{ runner.temp }}/prefix

    - name: Smoke test
      run: python3 smoketest/run.py --sudo
