// Code generated by esbuild; DO NOT EDIT!
"use strict";
(() => {
  // node_modules/preact/dist/preact.module.js
  var n;
  var l;
  var u;
  var t;
  var i;
  var r;
  var o;
  var e;
  var f;
  var c;
  var s;
  var a;
  var h;
  var p = {};
  var v = [];
  var y = /acit|ex(?:s|g|n|p|$)|rph|grid|ows|mnc|ntw|ine[ch]|zoo|^ord|itera/i;
  var d = Array.isArray;
  function w(n2, l3) {
    for (var u4 in l3) n2[u4] = l3[u4];
    return n2;
  }
  function g(n2) {
    n2 && n2.parentNode && n2.parentNode.removeChild(n2);
  }
  function _(l3, u4, t3) {
    var i4, r3, o3, e3 = {};
    for (o3 in u4) "key" == o3 ? i4 = u4[o3] : "ref" == o3 ? r3 = u4[o3] : e3[o3] = u4[o3];
    if (arguments.length > 2 && (e3.children = arguments.length > 3 ? n.call(arguments, 2) : t3), "function" == typeof l3 && null != l3.defaultProps) for (o3 in l3.defaultProps) void 0 === e3[o3] && (e3[o3] = l3.defaultProps[o3]);
    return m(l3, e3, i4, r3, null);
  }
  function m(n2, t3, i4, r3, o3) {
    var e3 = { type: n2, props: t3, key: i4, ref: r3, __k: null, __: null, __b: 0, __e: null, __c: null, constructor: void 0, __v: null == o3 ? ++u : o3, __i: -1, __u: 0 };
    return null == o3 && null != l.vnode && l.vnode(e3), e3;
  }
  function k(n2) {
    return n2.children;
  }
  function x(n2, l3) {
    this.props = n2, this.context = l3;
  }
  function S(n2, l3) {
    if (null == l3) return n2.__ ? S(n2.__, n2.__i + 1) : null;
    for (var u4; l3 < n2.__k.length; l3++) if (null != (u4 = n2.__k[l3]) && null != u4.__e) return u4.__e;
    return "function" == typeof n2.type ? S(n2) : null;
  }
  function C(n2) {
    var l3, u4;
    if (null != (n2 = n2.__) && null != n2.__c) {
      for (n2.__e = n2.__c.base = null, l3 = 0; l3 < n2.__k.length; l3++) if (null != (u4 = n2.__k[l3]) && null != u4.__e) {
        n2.__e = n2.__c.base = u4.__e;
        break;
      }
      return C(n2);
    }
  }
  function M(n2) {
    (!n2.__d && (n2.__d = true) && i.push(n2) && !$.__r++ || r !== l.debounceRendering) && ((r = l.debounceRendering) || o)($);
  }
  function $() {
    for (var n2, u4, t3, r3, o3, f4, c3, s3 = 1; i.length; ) i.length > s3 && i.sort(e), n2 = i.shift(), s3 = i.length, n2.__d && (t3 = void 0, o3 = (r3 = (u4 = n2).__v).__e, f4 = [], c3 = [], u4.__P && ((t3 = w({}, r3)).__v = r3.__v + 1, l.vnode && l.vnode(t3), j(u4.__P, t3, r3, u4.__n, u4.__P.namespaceURI, 32 & r3.__u ? [o3] : null, f4, null == o3 ? S(r3) : o3, !!(32 & r3.__u), c3), t3.__v = r3.__v, t3.__.__k[t3.__i] = t3, z(f4, t3, c3), t3.__e != o3 && C(t3)));
    $.__r = 0;
  }
  function I(n2, l3, u4, t3, i4, r3, o3, e3, f4, c3, s3) {
    var a3, h3, y3, d3, w3, g2, _2 = t3 && t3.__k || v, m3 = l3.length;
    for (f4 = P(u4, l3, _2, f4, m3), a3 = 0; a3 < m3; a3++) null != (y3 = u4.__k[a3]) && (h3 = -1 === y3.__i ? p : _2[y3.__i] || p, y3.__i = a3, g2 = j(n2, y3, h3, i4, r3, o3, e3, f4, c3, s3), d3 = y3.__e, y3.ref && h3.ref != y3.ref && (h3.ref && V(h3.ref, null, y3), s3.push(y3.ref, y3.__c || d3, y3)), null == w3 && null != d3 && (w3 = d3), 4 & y3.__u || h3.__k === y3.__k ? f4 = A(y3, f4, n2) : "function" == typeof y3.type && void 0 !== g2 ? f4 = g2 : d3 && (f4 = d3.nextSibling), y3.__u &= -7);
    return u4.__e = w3, f4;
  }
  function P(n2, l3, u4, t3, i4) {
    var r3, o3, e3, f4, c3, s3 = u4.length, a3 = s3, h3 = 0;
    for (n2.__k = new Array(i4), r3 = 0; r3 < i4; r3++) null != (o3 = l3[r3]) && "boolean" != typeof o3 && "function" != typeof o3 ? (f4 = r3 + h3, (o3 = n2.__k[r3] = "string" == typeof o3 || "number" == typeof o3 || "bigint" == typeof o3 || o3.constructor == String ? m(null, o3, null, null, null) : d(o3) ? m(k, { children: o3 }, null, null, null) : void 0 === o3.constructor && o3.__b > 0 ? m(o3.type, o3.props, o3.key, o3.ref ? o3.ref : null, o3.__v) : o3).__ = n2, o3.__b = n2.__b + 1, e3 = null, -1 !== (c3 = o3.__i = L(o3, u4, f4, a3)) && (a3--, (e3 = u4[c3]) && (e3.__u |= 2)), null == e3 || null === e3.__v ? (-1 == c3 && h3--, "function" != typeof o3.type && (o3.__u |= 4)) : c3 != f4 && (c3 == f4 - 1 ? h3-- : c3 == f4 + 1 ? h3++ : (c3 > f4 ? h3-- : h3++, o3.__u |= 4))) : n2.__k[r3] = null;
    if (a3) for (r3 = 0; r3 < s3; r3++) null != (e3 = u4[r3]) && 0 == (2 & e3.__u) && (e3.__e == t3 && (t3 = S(e3)), q(e3, e3));
    return t3;
  }
  function A(n2, l3, u4) {
    var t3, i4;
    if ("function" == typeof n2.type) {
      for (t3 = n2.__k, i4 = 0; t3 && i4 < t3.length; i4++) t3[i4] && (t3[i4].__ = n2, l3 = A(t3[i4], l3, u4));
      return l3;
    }
    n2.__e != l3 && (l3 && n2.type && !u4.contains(l3) && (l3 = S(n2)), u4.insertBefore(n2.__e, l3 || null), l3 = n2.__e);
    do {
      l3 = l3 && l3.nextSibling;
    } while (null != l3 && 8 == l3.nodeType);
    return l3;
  }
  function L(n2, l3, u4, t3) {
    var i4, r3, o3 = n2.key, e3 = n2.type, f4 = l3[u4];
    if (null === f4 || f4 && o3 == f4.key && e3 === f4.type && 0 == (2 & f4.__u)) return u4;
    if (t3 > (null != f4 && 0 == (2 & f4.__u) ? 1 : 0)) for (i4 = u4 - 1, r3 = u4 + 1; i4 >= 0 || r3 < l3.length; ) {
      if (i4 >= 0) {
        if ((f4 = l3[i4]) && 0 == (2 & f4.__u) && o3 == f4.key && e3 === f4.type) return i4;
        i4--;
      }
      if (r3 < l3.length) {
        if ((f4 = l3[r3]) && 0 == (2 & f4.__u) && o3 == f4.key && e3 === f4.type) return r3;
        r3++;
      }
    }
    return -1;
  }
  function T(n2, l3, u4) {
    "-" == l3[0] ? n2.setProperty(l3, null == u4 ? "" : u4) : n2[l3] = null == u4 ? "" : "number" != typeof u4 || y.test(l3) ? u4 : u4 + "px";
  }
  function F(n2, l3, u4, t3, i4) {
    var r3;
    n: if ("style" == l3) if ("string" == typeof u4) n2.style.cssText = u4;
    else {
      if ("string" == typeof t3 && (n2.style.cssText = t3 = ""), t3) for (l3 in t3) u4 && l3 in u4 || T(n2.style, l3, "");
      if (u4) for (l3 in u4) t3 && u4[l3] === t3[l3] || T(n2.style, l3, u4[l3]);
    }
    else if ("o" == l3[0] && "n" == l3[1]) r3 = l3 != (l3 = l3.replace(f, "$1")), l3 = l3.toLowerCase() in n2 || "onFocusOut" == l3 || "onFocusIn" == l3 ? l3.toLowerCase().slice(2) : l3.slice(2), n2.l || (n2.l = {}), n2.l[l3 + r3] = u4, u4 ? t3 ? u4.u = t3.u : (u4.u = c, n2.addEventListener(l3, r3 ? a : s, r3)) : n2.removeEventListener(l3, r3 ? a : s, r3);
    else {
      if ("http://www.w3.org/2000/svg" == i4) l3 = l3.replace(/xlink(H|:h)/, "h").replace(/sName$/, "s");
      else if ("width" != l3 && "height" != l3 && "href" != l3 && "list" != l3 && "form" != l3 && "tabIndex" != l3 && "download" != l3 && "rowSpan" != l3 && "colSpan" != l3 && "role" != l3 && "popover" != l3 && l3 in n2) try {
        n2[l3] = null == u4 ? "" : u4;
        break n;
      } catch (n3) {
      }
      "function" == typeof u4 || (null == u4 || false === u4 && "-" != l3[4] ? n2.removeAttribute(l3) : n2.setAttribute(l3, "popover" == l3 && 1 == u4 ? "" : u4));
    }
  }
  function O(n2) {
    return function(u4) {
      if (this.l) {
        var t3 = this.l[u4.type + n2];
        if (null == u4.t) u4.t = c++;
        else if (u4.t < t3.u) return;
        return t3(l.event ? l.event(u4) : u4);
      }
    };
  }
  function j(n2, u4, t3, i4, r3, o3, e3, f4, c3, s3) {
    var a3, h3, p3, v3, y3, _2, m3, b, S2, C3, M2, $2, P2, A2, H, L2, T2, F2, O2 = u4.type;
    if (void 0 !== u4.constructor) return null;
    128 & t3.__u && (c3 = !!(32 & t3.__u), o3 = [f4 = u4.__e = t3.__e]), (a3 = l.__b) && a3(u4);
    n: if ("function" == typeof O2) try {
      if (b = u4.props, S2 = "prototype" in O2 && O2.prototype.render, C3 = (a3 = O2.contextType) && i4[a3.__c], M2 = a3 ? C3 ? C3.props.value : a3.__ : i4, t3.__c ? m3 = (h3 = u4.__c = t3.__c).__ = h3.__E : (S2 ? u4.__c = h3 = new O2(b, M2) : (u4.__c = h3 = new x(b, M2), h3.constructor = O2, h3.render = B), C3 && C3.sub(h3), h3.props = b, h3.state || (h3.state = {}), h3.context = M2, h3.__n = i4, p3 = h3.__d = true, h3.__h = [], h3._sb = []), S2 && null == h3.__s && (h3.__s = h3.state), S2 && null != O2.getDerivedStateFromProps && (h3.__s == h3.state && (h3.__s = w({}, h3.__s)), w(h3.__s, O2.getDerivedStateFromProps(b, h3.__s))), v3 = h3.props, y3 = h3.state, h3.__v = u4, p3) S2 && null == O2.getDerivedStateFromProps && null != h3.componentWillMount && h3.componentWillMount(), S2 && null != h3.componentDidMount && h3.__h.push(h3.componentDidMount);
      else {
        if (S2 && null == O2.getDerivedStateFromProps && b !== v3 && null != h3.componentWillReceiveProps && h3.componentWillReceiveProps(b, M2), !h3.__e && (null != h3.shouldComponentUpdate && false === h3.shouldComponentUpdate(b, h3.__s, M2) || u4.__v == t3.__v)) {
          for (u4.__v != t3.__v && (h3.props = b, h3.state = h3.__s, h3.__d = false), u4.__e = t3.__e, u4.__k = t3.__k, u4.__k.some(function(n3) {
            n3 && (n3.__ = u4);
          }), $2 = 0; $2 < h3._sb.length; $2++) h3.__h.push(h3._sb[$2]);
          h3._sb = [], h3.__h.length && e3.push(h3);
          break n;
        }
        null != h3.componentWillUpdate && h3.componentWillUpdate(b, h3.__s, M2), S2 && null != h3.componentDidUpdate && h3.__h.push(function() {
          h3.componentDidUpdate(v3, y3, _2);
        });
      }
      if (h3.context = M2, h3.props = b, h3.__P = n2, h3.__e = false, P2 = l.__r, A2 = 0, S2) {
        for (h3.state = h3.__s, h3.__d = false, P2 && P2(u4), a3 = h3.render(h3.props, h3.state, h3.context), H = 0; H < h3._sb.length; H++) h3.__h.push(h3._sb[H]);
        h3._sb = [];
      } else do {
        h3.__d = false, P2 && P2(u4), a3 = h3.render(h3.props, h3.state, h3.context), h3.state = h3.__s;
      } while (h3.__d && ++A2 < 25);
      h3.state = h3.__s, null != h3.getChildContext && (i4 = w(w({}, i4), h3.getChildContext())), S2 && !p3 && null != h3.getSnapshotBeforeUpdate && (_2 = h3.getSnapshotBeforeUpdate(v3, y3)), T2 = (L2 = null != a3 && a3.type === k && null == a3.key) ? a3.props.children : a3, L2 && (a3.props.children = null), f4 = I(n2, d(T2) ? T2 : [T2], u4, t3, i4, r3, o3, e3, f4, c3, s3), h3.base = u4.__e, u4.__u &= -161, h3.__h.length && e3.push(h3), m3 && (h3.__E = h3.__ = null);
    } catch (n3) {
      if (u4.__v = null, c3 || null != o3) if (n3.then) {
        for (u4.__u |= c3 ? 160 : 128; f4 && 8 == f4.nodeType && f4.nextSibling; ) f4 = f4.nextSibling;
        o3[o3.indexOf(f4)] = null, u4.__e = f4;
      } else for (F2 = o3.length; F2--; ) g(o3[F2]);
      else u4.__e = t3.__e, u4.__k = t3.__k;
      l.__e(n3, u4, t3);
    }
    else null == o3 && u4.__v == t3.__v ? (u4.__k = t3.__k, u4.__e = t3.__e) : f4 = u4.__e = N(t3.__e, u4, t3, i4, r3, o3, e3, c3, s3);
    return (a3 = l.diffed) && a3(u4), 128 & u4.__u ? void 0 : f4;
  }
  function z(n2, u4, t3) {
    for (var i4 = 0; i4 < t3.length; i4++) V(t3[i4], t3[++i4], t3[++i4]);
    l.__c && l.__c(u4, n2), n2.some(function(u5) {
      try {
        n2 = u5.__h, u5.__h = [], n2.some(function(n3) {
          n3.call(u5);
        });
      } catch (n3) {
        l.__e(n3, u5.__v);
      }
    });
  }
  function N(u4, t3, i4, r3, o3, e3, f4, c3, s3) {
    var a3, h3, v3, y3, w3, _2, m3, b = i4.props, k3 = t3.props, x3 = t3.type;
    if ("svg" == x3 ? o3 = "http://www.w3.org/2000/svg" : "math" == x3 ? o3 = "http://www.w3.org/1998/Math/MathML" : o3 || (o3 = "http://www.w3.org/1999/xhtml"), null != e3) {
      for (a3 = 0; a3 < e3.length; a3++) if ((w3 = e3[a3]) && "setAttribute" in w3 == !!x3 && (x3 ? w3.localName == x3 : 3 == w3.nodeType)) {
        u4 = w3, e3[a3] = null;
        break;
      }
    }
    if (null == u4) {
      if (null == x3) return document.createTextNode(k3);
      u4 = document.createElementNS(o3, x3, k3.is && k3), c3 && (l.__m && l.__m(t3, e3), c3 = false), e3 = null;
    }
    if (null === x3) b === k3 || c3 && u4.data === k3 || (u4.data = k3);
    else {
      if (e3 = e3 && n.call(u4.childNodes), b = i4.props || p, !c3 && null != e3) for (b = {}, a3 = 0; a3 < u4.attributes.length; a3++) b[(w3 = u4.attributes[a3]).name] = w3.value;
      for (a3 in b) if (w3 = b[a3], "children" == a3) ;
      else if ("dangerouslySetInnerHTML" == a3) v3 = w3;
      else if (!(a3 in k3)) {
        if ("value" == a3 && "defaultValue" in k3 || "checked" == a3 && "defaultChecked" in k3) continue;
        F(u4, a3, null, w3, o3);
      }
      for (a3 in k3) w3 = k3[a3], "children" == a3 ? y3 = w3 : "dangerouslySetInnerHTML" == a3 ? h3 = w3 : "value" == a3 ? _2 = w3 : "checked" == a3 ? m3 = w3 : c3 && "function" != typeof w3 || b[a3] === w3 || F(u4, a3, w3, b[a3], o3);
      if (h3) c3 || v3 && (h3.__html === v3.__html || h3.__html === u4.innerHTML) || (u4.innerHTML = h3.__html), t3.__k = [];
      else if (v3 && (u4.innerHTML = ""), I("template" === t3.type ? u4.content : u4, d(y3) ? y3 : [y3], t3, i4, r3, "foreignObject" == x3 ? "http://www.w3.org/1999/xhtml" : o3, e3, f4, e3 ? e3[0] : i4.__k && S(i4, 0), c3, s3), null != e3) for (a3 = e3.length; a3--; ) g(e3[a3]);
      c3 || (a3 = "value", "progress" == x3 && null == _2 ? u4.removeAttribute("value") : void 0 !== _2 && (_2 !== u4[a3] || "progress" == x3 && !_2 || "option" == x3 && _2 !== b[a3]) && F(u4, a3, _2, b[a3], o3), a3 = "checked", void 0 !== m3 && m3 !== u4[a3] && F(u4, a3, m3, b[a3], o3));
    }
    return u4;
  }
  function V(n2, u4, t3) {
    try {
      if ("function" == typeof n2) {
        var i4 = "function" == typeof n2.__u;
        i4 && n2.__u(), i4 && null == u4 || (n2.__u = n2(u4));
      } else n2.current = u4;
    } catch (n3) {
      l.__e(n3, t3);
    }
  }
  function q(n2, u4, t3) {
    var i4, r3;
    if (l.unmount && l.unmount(n2), (i4 = n2.ref) && (i4.current && i4.current !== n2.__e || V(i4, null, u4)), null != (i4 = n2.__c)) {
      if (i4.componentWillUnmount) try {
        i4.componentWillUnmount();
      } catch (n3) {
        l.__e(n3, u4);
      }
      i4.base = i4.__P = null;
    }
    if (i4 = n2.__k) for (r3 = 0; r3 < i4.length; r3++) i4[r3] && q(i4[r3], u4, t3 || "function" != typeof n2.type);
    t3 || g(n2.__e), n2.__c = n2.__ = n2.__e = void 0;
  }
  function B(n2, l3, u4) {
    return this.constructor(n2, u4);
  }
  function D(u4, t3, i4) {
    var r3, o3, e3, f4;
    t3 == document && (t3 = document.documentElement), l.__ && l.__(u4, t3), o3 = (r3 = "function" == typeof i4) ? null : i4 && i4.__k || t3.__k, e3 = [], f4 = [], j(t3, u4 = (!r3 && i4 || t3).__k = _(k, null, [u4]), o3 || p, p, t3.namespaceURI, !r3 && i4 ? [i4] : o3 ? null : t3.firstChild ? n.call(t3.childNodes) : null, e3, !r3 && i4 ? i4 : o3 ? o3.__e : t3.firstChild, r3, f4), z(e3, u4, f4);
  }
  function J(n2) {
    function l3(n3) {
      var u4, t3;
      return this.getChildContext || (u4 = /* @__PURE__ */ new Set(), (t3 = {})[l3.__c] = this, this.getChildContext = function() {
        return t3;
      }, this.componentWillUnmount = function() {
        u4 = null;
      }, this.shouldComponentUpdate = function(n4) {
        this.props.value !== n4.value && u4.forEach(function(n5) {
          n5.__e = true, M(n5);
        });
      }, this.sub = function(n4) {
        u4.add(n4);
        var l4 = n4.componentWillUnmount;
        n4.componentWillUnmount = function() {
          u4 && u4.delete(n4), l4 && l4.call(n4);
        };
      }), n3.children;
    }
    return l3.__c = "__cC" + h++, l3.__ = n2, l3.Provider = l3.__l = (l3.Consumer = function(n3, l4) {
      return n3.children(l4);
    }).contextType = l3, l3;
  }
  n = v.slice, l = { __e: function(n2, l3, u4, t3) {
    for (var i4, r3, o3; l3 = l3.__; ) if ((i4 = l3.__c) && !i4.__) try {
      if ((r3 = i4.constructor) && null != r3.getDerivedStateFromError && (i4.setState(r3.getDerivedStateFromError(n2)), o3 = i4.__d), null != i4.componentDidCatch && (i4.componentDidCatch(n2, t3 || {}), o3 = i4.__d), o3) return i4.__E = i4;
    } catch (l4) {
      n2 = l4;
    }
    throw n2;
  } }, u = 0, t = function(n2) {
    return null != n2 && null == n2.constructor;
  }, x.prototype.setState = function(n2, l3) {
    var u4;
    u4 = null != this.__s && this.__s !== this.state ? this.__s : this.__s = w({}, this.state), "function" == typeof n2 && (n2 = n2(w({}, u4), this.props)), n2 && w(u4, n2), null != n2 && this.__v && (l3 && this._sb.push(l3), M(this));
  }, x.prototype.forceUpdate = function(n2) {
    this.__v && (this.__e = true, n2 && this.__h.push(n2), M(this));
  }, x.prototype.render = k, i = [], o = "function" == typeof Promise ? Promise.prototype.then.bind(Promise.resolve()) : setTimeout, e = function(n2, l3) {
    return n2.__v.__b - l3.__v.__b;
  }, $.__r = 0, f = /(PointerCapture)$|Capture$/i, c = 0, s = O(false), a = O(true), h = 0;

  // node_modules/preact/hooks/dist/hooks.module.js
  var t2;
  var r2;
  var u2;
  var i2;
  var o2 = 0;
  var f2 = [];
  var c2 = l;
  var e2 = c2.__b;
  var a2 = c2.__r;
  var v2 = c2.diffed;
  var l2 = c2.__c;
  var m2 = c2.unmount;
  var s2 = c2.__;
  function p2(n2, t3) {
    c2.__h && c2.__h(r2, n2, o2 || t3), o2 = 0;
    var u4 = r2.__H || (r2.__H = { __: [], __h: [] });
    return n2 >= u4.__.length && u4.__.push({}), u4.__[n2];
  }
  function d2(n2) {
    return o2 = 1, h2(D2, n2);
  }
  function h2(n2, u4, i4) {
    var o3 = p2(t2++, 2);
    if (o3.t = n2, !o3.__c && (o3.__ = [i4 ? i4(u4) : D2(void 0, u4), function(n3) {
      var t3 = o3.__N ? o3.__N[0] : o3.__[0], r3 = o3.t(t3, n3);
      t3 !== r3 && (o3.__N = [r3, o3.__[1]], o3.__c.setState({}));
    }], o3.__c = r2, !r2.__f)) {
      var f4 = function(n3, t3, r3) {
        if (!o3.__c.__H) return true;
        var u5 = o3.__c.__H.__.filter(function(n4) {
          return !!n4.__c;
        });
        if (u5.every(function(n4) {
          return !n4.__N;
        })) return !c3 || c3.call(this, n3, t3, r3);
        var i5 = o3.__c.props !== n3;
        return u5.forEach(function(n4) {
          if (n4.__N) {
            var t4 = n4.__[0];
            n4.__ = n4.__N, n4.__N = void 0, t4 !== n4.__[0] && (i5 = true);
          }
        }), c3 && c3.call(this, n3, t3, r3) || i5;
      };
      r2.__f = true;
      var c3 = r2.shouldComponentUpdate, e3 = r2.componentWillUpdate;
      r2.componentWillUpdate = function(n3, t3, r3) {
        if (this.__e) {
          var u5 = c3;
          c3 = void 0, f4(n3, t3, r3), c3 = u5;
        }
        e3 && e3.call(this, n3, t3, r3);
      }, r2.shouldComponentUpdate = f4;
    }
    return o3.__N || o3.__;
  }
  function y2(n2, u4) {
    var i4 = p2(t2++, 3);
    !c2.__s && C2(i4.__H, u4) && (i4.__ = n2, i4.u = u4, r2.__H.__h.push(i4));
  }
  function x2(n2) {
    var u4 = r2.context[n2.__c], i4 = p2(t2++, 9);
    return i4.c = n2, u4 ? (null == i4.__ && (i4.__ = true, u4.sub(r2)), u4.props.value) : n2.__;
  }
  function j2() {
    for (var n2; n2 = f2.shift(); ) if (n2.__P && n2.__H) try {
      n2.__H.__h.forEach(z2), n2.__H.__h.forEach(B2), n2.__H.__h = [];
    } catch (t3) {
      n2.__H.__h = [], c2.__e(t3, n2.__v);
    }
  }
  c2.__b = function(n2) {
    r2 = null, e2 && e2(n2);
  }, c2.__ = function(n2, t3) {
    n2 && t3.__k && t3.__k.__m && (n2.__m = t3.__k.__m), s2 && s2(n2, t3);
  }, c2.__r = function(n2) {
    a2 && a2(n2), t2 = 0;
    var i4 = (r2 = n2.__c).__H;
    i4 && (u2 === r2 ? (i4.__h = [], r2.__h = [], i4.__.forEach(function(n3) {
      n3.__N && (n3.__ = n3.__N), n3.u = n3.__N = void 0;
    })) : (i4.__h.forEach(z2), i4.__h.forEach(B2), i4.__h = [], t2 = 0)), u2 = r2;
  }, c2.diffed = function(n2) {
    v2 && v2(n2);
    var t3 = n2.__c;
    t3 && t3.__H && (t3.__H.__h.length && (1 !== f2.push(t3) && i2 === c2.requestAnimationFrame || ((i2 = c2.requestAnimationFrame) || w2)(j2)), t3.__H.__.forEach(function(n3) {
      n3.u && (n3.__H = n3.u), n3.u = void 0;
    })), u2 = r2 = null;
  }, c2.__c = function(n2, t3) {
    t3.some(function(n3) {
      try {
        n3.__h.forEach(z2), n3.__h = n3.__h.filter(function(n4) {
          return !n4.__ || B2(n4);
        });
      } catch (r3) {
        t3.some(function(n4) {
          n4.__h && (n4.__h = []);
        }), t3 = [], c2.__e(r3, n3.__v);
      }
    }), l2 && l2(n2, t3);
  }, c2.unmount = function(n2) {
    m2 && m2(n2);
    var t3, r3 = n2.__c;
    r3 && r3.__H && (r3.__H.__.forEach(function(n3) {
      try {
        z2(n3);
      } catch (n4) {
        t3 = n4;
      }
    }), r3.__H = void 0, t3 && c2.__e(t3, r3.__v));
  };
  var k2 = "function" == typeof requestAnimationFrame;
  function w2(n2) {
    var t3, r3 = function() {
      clearTimeout(u4), k2 && cancelAnimationFrame(t3), setTimeout(n2);
    }, u4 = setTimeout(r3, 100);
    k2 && (t3 = requestAnimationFrame(r3));
  }
  function z2(n2) {
    var t3 = r2, u4 = n2.__c;
    "function" == typeof u4 && (n2.__c = void 0, u4()), r2 = t3;
  }
  function B2(n2) {
    var t3 = r2;
    n2.__c = n2.__(), r2 = t3;
  }
  function C2(n2, t3) {
    return !n2 || n2.length !== t3.length || t3.some(function(t4, r3) {
      return t4 !== n2[r3];
    });
  }
  function D2(n2, t3) {
    return "function" == typeof t3 ? t3(n2) : t3;
  }

  // timefmt.ts
  var timeOptions = {
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
    timeZoneName: "short"
  };
  var dateOptions = {
    year: "numeric",
    month: "long",
    day: "numeric"
  };
  var timestampRegex = /^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:)(\d{2})(?:\.\d+)?(?:[+-]00:00|Z)$/;
  function formatUTCLocal(t3, locales) {
    const match = timestampRegex.exec(t3);
    if (!match) {
      return null;
    }
    const [, initial, second] = match;
    const d3 = /* @__PURE__ */ new Date(initial + "00Z");
    return formatDateLocal(d3, second, locales);
  }
  function formatDateLocal(d3, second, locales) {
    const date = d3.toLocaleDateString(locales, dateOptions);
    const parts = Intl.DateTimeFormat(locales, timeOptions).formatToParts(d3);
    let time = "";
    for (const { type, value } of parts) {
      switch (type) {
        case "hour":
        case "minute":
        case "timeZoneName":
        case "literal":
          time += value;
          break;
        case "second":
          time += second;
          break;
      }
    }
    return { date, time };
  }
  function formatNanoseconds(t3) {
    if (t3 >= 1e9) {
      return (t3 / 1e9).toFixed(3) + " s";
    }
    if (t3 >= 1e6) {
      return (t3 / 1e6).toFixed(3) + " ms";
    }
    if (t3 >= 1e3) {
      return (t3 / 1e3).toFixed(3) + " \xB5s";
    }
    return t3 + " ns";
  }
  function formatTAI(secs) {
    return formatDateTime(new Date(secs * 1e3).toISOString());
  }
  function formatDateTime(t3) {
    return t3.replace("T", " ").substring(0, 19);
  }

  // node_modules/preact/jsx-runtime/dist/jsxRuntime.module.js
  var f3 = 0;
  var i3 = Array.isArray;
  function u3(e3, t3, n2, o3, i4, u4) {
    t3 || (t3 = {});
    var a3, c3, p3 = t3;
    if ("ref" in p3) for (c3 in p3 = {}, t3) "ref" == c3 ? a3 = t3[c3] : p3[c3] = t3[c3];
    var l3 = { type: e3, props: p3, key: n2, ref: a3, __k: null, __: null, __b: 0, __e: null, __c: null, constructor: void 0, __v: --f3, __i: -1, __u: 0, __source: i4, __self: u4 };
    if ("function" == typeof e3 && (a3 = e3.defaultProps)) for (c3 in a3) void 0 === p3[c3] && (p3[c3] = a3[c3]);
    return l.vnode && l.vnode(l3), l3;
  }

  // svg.tsx
  function SkyView(satellites) {
    const SIZE = 200;
    const RADIUS = SIZE / 2;
    const STROKE_PAD = 1;
    const toXY = (az, el) => {
      const r3 = (90 - el) / 90 * RADIUS;
      const rad = (az - 90) * (Math.PI / 180);
      const x3 = RADIUS + r3 * Math.cos(rad);
      const y3 = RADIUS + r3 * Math.sin(rad);
      return [x3, y3];
    };
    const tracked = satellites.filter((sv) => sv.cno > 0);
    return /* @__PURE__ */ u3(
      "svg",
      {
        viewBox: `${-STROKE_PAD} ${-STROKE_PAD} ${SIZE + 2 * STROKE_PAD} ${SIZE + 2 * STROKE_PAD}`,
        preserveAspectRatio: "xMidYMid meet",
        class: "w-full h-auto",
        xmlns: "http://www.w3.org/2000/svg",
        children: [
          /* @__PURE__ */ u3("circle", { cx: RADIUS, cy: RADIUS, r: RADIUS, class: "stroke-gray-400 fill-none stroke-[1]" }),
          [15, 30, 45, 60].map((el) => /* @__PURE__ */ u3(
            "circle",
            {
              cx: RADIUS,
              cy: RADIUS,
              r: (90 - el) / 90 * RADIUS,
              class: "stroke-gray-200 fill-none stroke-[0.5]"
            },
            el
          )),
          (() => {
            const outerR = RADIUS;
            const innerR = (90 - 60) / 90 * RADIUS;
            return Array.from({ length: 12 }, (_2, i4) => {
              const angle = i4 * 30;
              const rad = (angle - 90) * (Math.PI / 180);
              const x1 = RADIUS + outerR * Math.cos(rad);
              const y1 = RADIUS + outerR * Math.sin(rad);
              const x22 = RADIUS + innerR * Math.cos(rad);
              const y22 = RADIUS + innerR * Math.sin(rad);
              return /* @__PURE__ */ u3(
                "line",
                {
                  x1,
                  y1,
                  x2: x22,
                  y2: y22,
                  class: "stroke-gray-300 stroke-[0.5]"
                },
                `radial-${angle}`
              );
            });
          })(),
          /* @__PURE__ */ u3("text", { x: RADIUS, y: 10, "text-anchor": "middle", class: "fill-gray-500 text-[6px]", children: "N" }),
          tracked.map((sv) => {
            const [x3, y3] = toXY(sv.azimuth, sv.elevation);
            return /* @__PURE__ */ u3(
              "text",
              {
                x: x3,
                y: y3,
                "text-anchor": "middle",
                "dominant-baseline": "middle",
                class: `text-[3px] font-bold ${colorClassFor(sv.svid)} ${opacityClassFor(sv.cno)}`,
                children: sv.svid
              },
              sv.svid
            );
          })
        ]
      }
    );
  }
  function opacityClassFor(cno) {
    if (cno < 25) return "opacity-20";
    if (cno < 30) return "opacity-40";
    if (cno < 35) return "opacity-60";
    if (cno < 42) return "opacity-75";
    if (cno < 50) return "opacity-90";
    return "opacity-100";
  }
  function colorClassFor(svid) {
    const prefix = svid[0];
    switch (prefix) {
      case "G":
      // GPS
      case "S":
        return "fill-blue-600 dark:fill-blue-400";
      case "E":
        return "fill-green-600 dark:fill-green-400";
      case "C":
        return "fill-red-600 dark:fill-red-400";
      case "R":
        return "fill-fuchsia-600 dark:fill-fuchsia-400";
      case "J":
        return "fill-orange-600 dark:fill-orange-400";
      case "I":
        return "fill-yellow-600 dark:fill-yellow-300";
      default:
        return "fill-gray-600 dark:fill-gray-400";
    }
  }
  function SignalGraph(satellites, maxSatelliteCount, isDoubleRow) {
    const WIDTH = 300;
    const MARGIN = { top: 20, right: 10, bottom: 10, left: 30 };
    const VERTICAL_MARGINS = MARGIN.top + MARGIN.bottom;
    const CHART_WIDTH = WIDTH - MARGIN.left - MARGIN.right;
    const MIN_HEIGHT = 200;
    const SINGLE_ROW_HEIGHT = 240;
    const DOUBLE_ROW_HEIGHT = 480;
    var height = isDoubleRow ? DOUBLE_ROW_HEIGHT : SINGLE_ROW_HEIGHT;
    var chartHeight = height - VERTICAL_MARGINS;
    const MIN_SATELLITES = 4;
    const MAX_CNO = 55;
    const MIN_BAR_HEIGHT = 14;
    const MAX_BAR_HEIGHT = 24;
    const BAR_SPACING = 4;
    const trackedSatellites = satellites.filter((sv) => sv.cno > 0);
    const sortedSatellites = [...trackedSatellites].sort((a3, b) => {
      if (a3.svid[0] !== b.svid[0]) {
        return a3.svid[0].localeCompare(b.svid[0]);
      }
      const aNum = parseInt(a3.svid.substring(1));
      const bNum = parseInt(b.svid.substring(1));
      return aNum - bNum;
    });
    const barHeight = Math.min(
      MAX_BAR_HEIGHT,
      Math.max(MIN_BAR_HEIGHT, chartHeight / Math.max(MIN_SATELLITES, maxSatelliteCount))
    );
    const spacedBarHeight = barHeight + BAR_SPACING;
    const gridLineHeight = sortedSatellites.length * spacedBarHeight - BAR_SPACING;
    chartHeight = maxSatelliteCount * spacedBarHeight;
    height = Math.max(MIN_HEIGHT, chartHeight + VERTICAL_MARGINS);
    return /* @__PURE__ */ u3(
      "svg",
      {
        viewBox: `0 0 ${WIDTH} ${height}`,
        preserveAspectRatio: "xMidYMid meet",
        class: "w-full h-full",
        xmlns: "http://www.w3.org/2000/svg",
        children: /* @__PURE__ */ u3("g", { transform: `translate(${MARGIN.left}, ${MARGIN.top})`, children: [
          [0, 10, 20, 30, 40, 50].map((value) => /* @__PURE__ */ u3(
            "text",
            {
              x: value / MAX_CNO * CHART_WIDTH,
              y: -5,
              "text-anchor": "middle",
              "dominant-baseline": "auto",
              class: "fill-gray-600 dark:fill-gray-100 text-xs",
              children: value
            },
            `x-label-${value}`
          )),
          [0, 10, 20, 30, 40, 50].map((value) => /* @__PURE__ */ u3(
            "line",
            {
              x1: value / MAX_CNO * CHART_WIDTH,
              y1: 0,
              x2: value / MAX_CNO * CHART_WIDTH,
              y2: gridLineHeight,
              class: "stroke-gray-200 dark:stroke-gray-700 stroke-[0.5]"
            },
            `grid-${value}`
          )),
          sortedSatellites.map((sv, i4) => {
            const cno = Math.min(sv.cno, MAX_CNO);
            const barWidth = cno / MAX_CNO * CHART_WIDTH;
            return /* @__PURE__ */ u3("g", { transform: `translate(0, ${i4 * spacedBarHeight})`, children: [
              /* @__PURE__ */ u3(
                "text",
                {
                  x: -5,
                  y: barHeight / 2,
                  "text-anchor": "end",
                  "dominant-baseline": "central",
                  class: "text-[10px] tabular-nums fill-gray-800 dark:fill-gray-200",
                  children: sv.svid
                }
              ),
              /* @__PURE__ */ u3(
                "rect",
                {
                  x: 0,
                  y: 0,
                  width: barWidth,
                  height: barHeight,
                  class: colorClassFor(sv.svid)
                }
              )
            ] }, sv.svid);
          })
        ] })
      }
    );
  }

  // dashboard.tsx
  var EventSourceContext = J(null);
  var EVENT_TYPES = ["satellites", "time", "phc", "survey", "version", "init"];
  var Dashboard = () => {
    const context = x2(EventSourceContext);
    const [events, setEvents] = d2({});
    y2(() => {
      const handler = (type) => (e3) => {
        const parsedEvents = parseSSEMessage(type, e3.data);
        for (const [eventType, eventData] of parsedEvents) {
          const obj = validateEvent(eventType, eventData);
          if (obj !== null) {
            setEvents((prev) => ({ ...prev, [eventType]: obj }));
          }
        }
      };
      for (const type of EVENT_TYPES) {
        context.addEventListener(type, handler(type));
      }
      return () => {
        for (const type of EVENT_TYPES) {
          context.removeEventListener(type, handler(type));
        }
      };
    }, []);
    return /* @__PURE__ */ u3(CardsElement, { children: [
      events.satellites && /* @__PURE__ */ u3(SkyViewCard, { svs: events.satellites.svs }),
      events.satellites && /* @__PURE__ */ u3(SignalGraphCard, { svs: events.satellites.svs }),
      events.time && /* @__PURE__ */ u3(PropertyCard, { title: "Current GPS Time", data: events.time, format: timeFormat }),
      events.phc && /* @__PURE__ */ u3(PropertyCard, { title: "PTP Hardware Clock", data: events.phc, format: phcFormat }),
      events.version && /* @__PURE__ */ u3(PropertyCard, { title: "GPS Receiver Version", data: events.version, format: versionFormat }),
      events.survey && /* @__PURE__ */ u3(PropertyCard, { title: "Survey-in Status", data: events.survey, format: surveyFormat })
    ] });
  };
  function parseSSEMessage(type, data) {
    try {
      const parsed = JSON.parse(data);
      if (type !== "init") {
        return [[type, parsed]];
      }
      if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
        console.warn(`Invalid init event data:`, parsed);
        return [];
      }
      const results = [];
      for (const key in parsed) {
        if (key === "init") {
          console.warn("init event cannot have an init key in its data");
        } else {
          results.push([key, parsed[key]]);
        }
      }
      return results;
    } catch (err) {
      console.warn(`Error parsing ${type} event:`, err);
      return [];
    }
  }
  function validateEvent(type, data) {
    if (type === "init" || !EVENT_TYPES.includes(type)) {
      console.warn(`Invalid event type: ${type}`);
      return null;
    }
    if (!data || typeof data !== "object" || Array.isArray(data)) {
      console.warn(`Invalid ${type} event data: not an object`, data);
      return null;
    }
    switch (type) {
      case "satellites":
        const svs = data.svs;
        if (!svs || !Array.isArray(svs)) {
          console.warn("Invalid satellites event: missing svs array", data);
          return null;
        }
        break;
    }
    return data;
  }
  var CardsElement = ({ children }) => {
    return /* @__PURE__ */ u3("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 p-4", children });
  };
  var CardElement = ({ children, title }) => {
    return /* @__PURE__ */ u3("div", { className: "p-4 rounded-lg mb-4 shadow-md break-inside-avoid bg-white dark:bg-gray-800 border-l-4 border-orange-500 h-full flex flex-col", children: [
      title && /* @__PURE__ */ u3("h3", { className: "mt-0 mb-4 text-xl cursor-pointer text-blue-600 dark:text-blue-400", children: title }),
      /* @__PURE__ */ u3("div", { className: "transition-all duration-300 overflow-hidden flex-grow", children })
    ] });
  };
  var FieldElement = ({ children, desc }) => {
    return /* @__PURE__ */ u3("div", { className: "flex justify-between text-base mb-2 text-gray-600 dark:text-gray-300", children: [
      /* @__PURE__ */ u3("span", { className: "font-bold text-gray-800 dark:text-blue-200", children: [
        desc,
        ":"
      ] }),
      /* @__PURE__ */ u3("span", { className: "tabular-nums text-gray-900 dark:text-gray-100", children })
    ] });
  };
  var PropertyCard = ({ title, data, format }) => {
    const fields = [];
    addFields(fields, data, format);
    return /* @__PURE__ */ u3(CardElement, { title, children: fields.map(([desc, value]) => /* @__PURE__ */ u3(FieldElement, { desc, children: value })) });
  };
  function addFields(fields, state, format) {
    for (const [key, f4] of Object.entries(format)) {
      if (!(key in state)) {
        continue;
      }
      if (typeof f4 === "function") {
        const formatted = f4(state[key], state);
        fields.push(...formatted);
      } else {
        const [desc, formatter] = f4;
        const val = state[key];
        const formatted = formatter ? formatter(val) : val;
        fields.push([desc, formatted]);
      }
    }
  }
  var versionFormat = {
    hw: ["Hardware"],
    mod: ["Module"],
    prot: ["UBX Protocol", (arg) => `${arg.major}.${arg.minor}`],
    fw: ["Firmware", (arg) => `${arg.productCategory} ${arg.major}.${arg.minor}`]
  };
  var timeFormat = {
    utc: formatUTC,
    tai: ["TAI", formatTAI]
  };
  var phcFormat = {
    syncState: ["State"],
    offset: ["Offset from GPS", formatNanoseconds],
    freq: ["Frequency offset", (arg) => `${arg.toFixed(2)} ppb`],
    stepCount: (count, obj) => [
      ["Stepped", count + (obj.stepCountChanging ? "/" + (count + 1) : "") + " times"]
    ]
  };
  var surveyFormat = {
    accuracy: ["Accuracy", (arg) => `${arg.toFixed(4)} m`],
    x: ["ECEF X", formatECEF],
    y: ["ECEF Y", formatECEF],
    z: ["ECEF Z", formatECEF],
    latLon: formatLL,
    alt: ["Altitude", formatAlt],
    obsCount: ["Observations"],
    obsTime: ["Observation time"],
    valid: ["Valid", formatBoolean],
    inProgress: ["In Progress", formatBoolean]
  };
  function formatECEF(arg) {
    return arg.toFixed(4);
  }
  function formatLL(arg, _obj) {
    if (isNaN(arg[0]) || isNaN(arg[1])) {
      return [];
    }
    return [
      ["Coordinates", /* @__PURE__ */ u3("a", { href: mapsURL(arg), target: "_blank", className: "underline hover:text-blue-500", children: coordsToString(arg, 5) })]
    ];
  }
  function mapsURL(arg) {
    return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(coordsToString(arg, 7))}`;
  }
  function coordsToString(arg, nDigits) {
    return `${arg[0].toFixed(nDigits)},${arg[1].toFixed(nDigits)}`;
  }
  function formatAlt(arg) {
    if (isNaN(arg)) {
      return "";
    }
    return `${arg.toFixed(2)} m`;
  }
  function formatUTC(utc) {
    const dt = formatUTCLocal(utc);
    if (dt == null) {
      return [];
    }
    const { date, time } = dt;
    return [
      ["Local time", time],
      ["Local date", date],
      ["UTC", formatDateTime(utc)]
    ];
  }
  function formatBoolean(arg) {
    return arg ? "Yes" : "No";
  }
  var SkyViewCard = ({ svs }) => {
    return /* @__PURE__ */ u3("div", { className: "md:col-span-2 lg:col-span-2 md:row-span-2 lg:row-span-2", children: /* @__PURE__ */ u3(CardElement, { children: SkyView(svs) }) });
  };
  var SignalGraphCard = ({ svs }) => {
    const [maxSatelliteCount, setMaxSatelliteCount] = d2(0);
    y2(() => {
      const currentCount = svs.filter((sv) => sv.cno > 0).length;
      if (currentCount > maxSatelliteCount) {
        setMaxSatelliteCount(currentCount);
      }
    }, [svs, maxSatelliteCount]);
    const isDoubleRow = maxSatelliteCount >= 15;
    const rowSpanClass = isDoubleRow ? "md:row-span-2 lg:row-span-2" : "";
    return /* @__PURE__ */ u3("div", { className: `${rowSpanClass} h-full`, children: /* @__PURE__ */ u3(CardElement, { title: "Signal Levels", children: SignalGraph(svs, maxSatelliteCount, isDoubleRow) }) });
  };

  // app.tsx
  function createEventSource() {
    const base = new URL(window.location.href);
    const sseURL = base.origin + base.pathname + "/sse";
    return new EventSource(sseURL);
  }
  var root = document.getElementById("root");
  D(
    /* @__PURE__ */ u3(EventSourceContext.Provider, { value: createEventSource(), children: /* @__PURE__ */ u3(Dashboard, {}) }),
    root
  );
})();
