#!/usr/bin/env node

import * as esbuild from 'esbuild'

await esbuild.build({
  entryPoints: ['app.tsx'],
  banner: {
    js: '// Code generated by esbuild; DO NOT EDIT!'
  },
  bundle: true,
  outfile: 'app.js',
})